# Generated by Django 4.2.16 on 2024-10-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('formed', 'Formed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=9, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Formed At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_analyses_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_analyses_moderated', to=settings.AUTH_USER_MODEL, verbose_name='Moderator')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='FlowAnalysisStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main')),
                ('flow_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flowanalysis', verbose_name='Flow Analysis')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Flow Analysis-Station',
                'verbose_name_plural': 'Flow Analysis-Stations',
                'unique_together': {('flow_analysis', 'station')},
            },
        ),
    ]
