# Generated by Django 4.2.16 on 2024-11-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_flowanalysis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowanalysis',
            name='flow',
        ),
        migrations.AddField(
            model_name='flowanalysisstation',
            name='flow',
            field=models.FloatField(null=True),
        ),
    ]
